title: "Christoforos Kapsalis"
tagline: "Marketing · BI"
description: "Graduate‑level data‑science and analytics portfolio"
url: "https://c-kapsalis.github.io"
baseurl: "/portfolio-website"          # keeps URLs correct for project pages repo

remote_theme: "mmistakes/minimal-mistakes@4.27.3"   # latest release as of Aug 2025
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache  # optional

search: true 

# navigation links (theme reads this)
navigation:
  - title: "Projects"
    url: "/projects"
  - title: "Blog"
    url: "/blog"
  - title: "About"
    url: "/about"

collections:
  projects:
    output: true
    permalink: /projects/:name
