title: "Christoforos Kapsalis"
tagline: "Marketing Analytics · BI · Fulbright MSc Marketing"
description: "Graduate‑level data‑science and analytics portfolio"
baseurl: "/portfolio-website"          # keeps URLs correct for project pages repo
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-sitemap

# navigation links (theme reads this)
navigation:
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"

collections:
  projects:
    output: true
    permalink: /projects/:name
