# Site settings
title: "Christoforos Kapsalis"
tagline: "Marketing · BI"
description: "Graduate‑level data‑science and analytics portfolio"
url: "https://c-kapsalis.github.io"
baseurl: "/portfolio-website"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Plugins\plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Search
search: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Nav (reads _data/navigation.yml if present)
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"