# Site settings
title: "Christoforos Kapsalis"
description: "Graduate-Level Marketing Analytics & Growth Insights"
url: "https://c-kapsalis.github.io"
baseurl: "/portfolio-website"
repository: "C-Kapsalis/portfolio-website"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination settings (REQUIRED for blog posts to show)
paginate: 5
paginate_path: /blog/page:num/

# Collections configuration (REQUIRED for projects)
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Enable collections processing
collections_dir: .

# Ensure proper styling
minimal_mistakes_skin: "default" # or "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Include pages
include:
  - _pages

# Make sure these are set
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      title_separator: "|"
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Author information
author:
  name: "Christoforos Kapsalis"
  bio: "Your bio here"
  location: "Your location"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/C-Kapsalis"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "your-linkedin-url"