title:  "Christoforos Kapsalis"
tagline: "Marketing Analytics • BI • Data Science Projects"
baseurl: "/portfolio-website"      # <‑‑ keep exactly if repo is portfolio‑website
theme: minima
plugins:
  - jekyll-sitemap
